server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8777
management:
  endpoints:
    web:
      base-path: /actuator
# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.28.8.170:3306/permission?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/*.xml
#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wwmxd.generator.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


